//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int req_id { get; set; }
        public string items { get; set; }
        public System.DateTime exp_date { get; set; }
        public string status { get; set; }
        public int r_id { get; set; }
        public Nullable<int> e_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
