//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int r_id { get; set; }
        public string r_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
